import sys
print("Starting imports...")
import asyncio; print("asyncio")
import json; print("json")
import math; print("math")
import time; print("time")
import traceback; print("traceback")
from datetime import datetime; print("datetime")
import websockets; print("websockets")
import httpx; print("httpx")
from fastapi import FastAPI, WebSocket, WebSocketDisconnect; print("fastapi")
from fastapi.middleware.cors import CORSMiddleware; print("cors")
from pydantic import BaseModel; print("pydantic")
from typing import List, Dict; print("typing")
from strategies import HighFrequencyScalper, TrendScaler; print("strategies")
print("DONE IMPORTS")
